baseurl: "https://blog.wiseai.cn/"
languageCode: "zh-cn"
title: "WiseAI的博客"
theme: "hugo-tania"
paginate: 10

publishdir: "docs/"

disqusShortname: https-hugo-tania-netlify-app

copyright: "陇ICP备15000157号"

author:
  name: "WiseAI"

params:
  # Emoji will show before the blog title on site navbar.
  titleEmoji: ✨  
  # Logo will show before the blog title on site navbar.
  titleLogo: 
  #titleLogo: favicon.ico
  
  # Enable float footnotes.
  # Default to true
  enableFootnotes: true
  
  siteName: "wiseai的备忘录"
  siteDesc: "Linux golang"
  author: "wiseai"

  colorScheme:
    # Enable toggle colorScheme
    # Default to true
    toggle: true
    # Default colorScheme
    # Default to auto
    default: auto

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow: 10

  # Show your socail information with icon on index bio with `_index.md` content.
  socialOptions:
    # dev-to:
    # email: fy@junzhe.net
    # facebook:
    # github:
    # instagram:
    # linkedin:
    # medium:
    # stack-overflow:
    # steam:
    # telegram:
    # twitter:
    # twitch:
    # whatsapp:
  
  # Comments settings
  comments:
    enabled: false
    provider: giscus

    giscus:
      repo: WingLim/hugo-tania
      id: MDEwOlJlcG9zaXRvcnkzMTYyNjQzMDc=
      category:
        name: Comments
        id: DIC_kwDOEtnPc84B_WKP
  text: 
    - content: "不经他人苦，莫劝他人善。"
    - content: "内心强大到混蛋，比什么都好！"
    - content: "规范流程比制定制度更重要！"
    - content: "祁连卧北雪，大漠壮雄关。"
    - content: "要么忙于生存，要么赶紧去死！"
    - content: "成功和不成功之间，只差一次坚持！"
  since: "2017"

menu:
  header:
    - name: 文章
      weight: "1"
      url: "articles/"
    - name: 关键字 
      weight: "3"
      url: "tags/"
    - name: 分类
      weight: "2"
      url: "categories/"      
  footer:
    - name: 孤鸟之歌
      weight: 1
      url: "https://wiseai.gitee.io/pages/gnzg/index.html"
    - name: 生成随机字符
      weight: 1
      url: "https://wiseai.gitee.io/pages/mm/index.html"
    - name: MarkDown
      weight: 2
      url: "https://wiseai.gitee.io/pages/md/index.html"
    - name: Gitee
      weight: 3
      url: "https://gitee.com/"
    - name: Github
      weight: 4
      url: "https://github.com/"
    - name: OSCHINA
      weight: 5
      url: "https://www.oschina.net/"
    - name: the way to go
      weight: 6
      url: "https://gitee.com/wiseai/the-way-to-go_ZH_CN/blob/master/eBook/directory.md"
    - name: GoFrame
      weight: 7
      url: "https://goframe.org/display/gf"
    - name: 阿里云盘
      weight: 8
      url: "https://www.aliyundrive.com/"
    - name: bootstrap文档
      weight: 9
      url: "https://www.bootstrap.cn/"
    - name: 千图
      weight: 10
      url: "https://www.58pic.com/"
    - name: 七牛云
      weight: 11
      url: "https://marketing.qiniu.com/"
    - name: 西瓜视频
      weight: 12
      url: "https://www.ixigua.com/"
    - name: 鱼缸计算
      weight: 13
      url: "https://wiseai.gitee.io/pages/yugang/index.html"
    - name: RSS
      weight: 100
      url: "index.xml"
    - name: 参考文章
      weight: 100
      url: "https://mp.weixin.qq.com/s/K2Dpw7yg8Y5Z_P4Jm6f8Tw"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

# outputs:
#   home: ["HTML", "RSS", "JSON"]
