baseurl: "https://blog.wiseai.cn"
languageCode: "zh-cn"
title: "wiseai的博客"
theme: "hugo-tania"
paginate: 10

publishdir: "docs/"

disqusShortname: https-hugo-tania-netlify-app

params:
  # Emoji will show before the blog title on site navbar.
  titleEmoji: ✨  
  # Logo will show before the blog title on site navbar.
  titleLogo: 
  #titleLogo: favicon.ico
  
  # Enable float footnotes.
  # Default to true
  enableFootnotes: true
  
  siteName: "wiseai的备忘录"
  siteDesc: "Linux golang"
  author: "wiseai"

  colorScheme:
    # Enable toggle colorScheme
    # Default to true
    toggle: true
    # Default colorScheme
    # Default to auto
    default: auto

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow: 10

  # Show your socail information with icon on index bio with `_index.md` content.
  socialOptions:
    # dev-to:
    #email: fy@junzhe.net
    # facebook:
    # github:
    # instagram:
    # linkedin:
    # medium:
    # stack-overflow:
    # steam:
    # telegram:
    # twitter:
    # twitch:
    # whatsapp:
  
  # Comments settings
  comments:
    enabled: false
    provider: giscus

    giscus:
      repo: WingLim/hugo-tania
      id: MDEwOlJlcG9zaXRvcnkzMTYyNjQzMDc=
      category:
        name: Comments
        id: DIC_kwDOEtnPc84B_WKP

menu:
  header:
    - name: 文章
      weight: "1"
      url: "articles/"
    - name: 关键字 
      weight: "3"
      url: "tags/"
    - name: 分类
      url: "categories/"
      weight: "2"
  footer:
    - name: RSS
      url: "index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS", "JSON"]
